packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

overrides:
  deepmerge-ts: "^8.0.2"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "argon2"
  - "esbuild"
  - "msw"
  - "prisma"
  - "protobufjs"

minimumReleaseAge: 0

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  argon2: true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
